### ISSUE TITLE
Change UI design 

### ISSUE THREAD

**Issue by sontrinh16** [notional-labs/anone-nft-market#2]
- [ ] remove the stripe
- [ ] filter design need to be fix ( look too messy) for reference: [link](https://opensea.io/assets?search[resultModel]=ASSETS)

![Screenshot from 2022-04-25 10-59-05](https://user-images.githubusercontent.com/48055119/165018604-22fe1747-ef4b-4745-82eb-aafa2aa6b4cb.png)

**Comment by HuydZzz** [comment]
https://www.figma.com/file/9vir7UND0VzdyfKO5tXMHP/Another-1-Sneaker-NFT-2?node-id=705%3A1831

please check it again I edited it a bit. Top collection and Top NFT I changed the design to make it easier for users to use
